@startuml

autonumber

participant ":RoomRoute" as Route
participant ":CreateRoomController" as Controller
participant ":CreateRoomService" as Service
participant ":Room" as Room
participant ":RoomRepo" as Repo
participant ":RoomPersistence" as Schema
participant ":RoomMap" as Map
participant ":RoomDTO" as DTO
participant ":FloorRepo" as FloorRepo
participant ":FloorPersistence" as FloorPersistence
participant ":Floor" as Floor

?o->Route: POST
activate Route

Route -> Controller: createRoom(req, res, next)
activate Controller

Controller -> Map: toDto(req.body)
activate Map
Controller <-- Map
deactivate Map

Controller -> Service: createRoom(roomDto)
activate Service


Service -> Room: room = create(roomProps)

Service -> Repo: save(room)
activate Repo

Repo -> Schema: save
deactivate Repo

Service -> FloorRepo: floor = find(floor)
activate FloorRepo
FloorRepo -> FloorPersistence: find
activate FloorPersistence
FloorRepo <-- FloorPersistence
deactivate FloorPersistence
Service <-- FloorRepo
deactivate FloorRepo

Service -> Floor: addRoom(room)

Service -> FloorRepo: save(floor)
activate FloorRepo

FloorRepo-> FloorPersistence: save
deactivate FloorRepo

Service -> Map:toDto(room)
activate Map
Map -> DTO: create
deactivate Map

Service --> Controller:
deactivate Service

Controller --> Route: success
deactivate Controller

<--Route:



@enduml
