@startuml

autonumber

participant ":RoomRoute" as Route
participant ":CreateRoomController" as Controller
participant ":CreateRoomService" as Service
participant ":Room"
participant ":RoomRepo" as Repo
participant ":RoomMap" as Map
participant ":RoomDTO" as DTO
participant ":FloorRepo" as FloorRepo
participant ":Floor"
database Database

?o->Route: POST
activate Route

Route -> Controller: createRoom(req, res, next)
activate Controller

Controller -> Map: toDto(req.body)
activate Map

Controller -> Service: createRoom(roomDto)
activate Service


Service -> Room: room = create(roomProps)

Service -> Repo: save(room)
activate Repo

Repo -> Database: save
deactivate Repo

Service -> FloorRepo: floor = find(floor)
activate FloorRepo
Service <-- FloorRepo
Service -> Floor: addRoom(room)
Service -> FloorRepo: save(floor)

FloorRepo-> Database: save
deactivate FloorRepo

Service -> Map:toDto(room)

Map -> DTO: create
deactivate Map

Service --> Controller:
deactivate Service

alt success
Controller --> Route: code 201
else insuccess
Controller --> Route: code 402
deactivate Controller
end alt
<--Route:



@enduml
