@startuml

autonumber

participant ":ElevatorRoute" as Route
participant ":EditElevatorController" as Controller
participant ":EditElevatorService" as Service
participant ":Elevator"
participant ":ElevatorRepo" as Repo
participant ":ElevatorSchema" as Schema
participant ":ElevatorMap" as Map
participant ":ElevatorDTO" as DTO
participant ":FloorRepo" as FloorRepo
participant ":FloorSchema" as FloorSchema
participant ":Floor"


?o->Route: PUT
activate Route

Route -> Controller: editElevator(req, res, next)
activate Controller

Controller -> Map: toDto(req.body)
activate Map

Controller -> Service: editElevator(elevatorDto)
activate Service


Service -> Room: room = create(elevatorProps)

Service -> Repo: save(elevator)
activate Repo

Repo -> Schema: save
deactivate Repo

Service -> FloorRepo: floor = find(floor)
activate FloorRepo
Service <-- FloorRepo
Service -> Floor: addRoom(room)
Service -> FloorRepo: save(floor)

deactivate FloorRepo

Service -> Map:toDto(room)

Map -> DTO: create
deactivate Map

Service --> Controller:
deactivate Service

alt success
Controller --> Route: code 201
else insuccess
Controller --> Route: code 402
deactivate Controller
end alt
<--Route:



@enduml
