@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Campus Manager" as CM


activate System
CM -> System: List elevators in building 
CM <-- System: List of elevators
deactivate System

@enduml