@startuml processLevel1
'https://plantuml.com/sequence-diagram

autonumber
participant Vizualization
participant MasterDataBuilding

?o->Vizualization : loadFloorMap
activate Vizualization

Vizualization -> MasterDataBuilding : loadFloorMap
activate MasterDataBuilding

MasterDataBuilding --> Vizualization
deactivate MasterDataBuilding

<--Vizualization
deactivate Vizualization

@enduml