@startuml

autonumber

participant ":FloorRoute" as Route
participant ":ListPassagewaysBetween2BuildingsController" as Controller
participant ":ListPassagewaysBetween2BuildingsService" as Service
participant ":BuildingRepo" as BuildingRepo
participant ":BuildingSchema" as BuildingSchema
participant ":IListPassagewaysBetween2BuildingsDTO" as DTO

participant ":FloorRepo" as FloorRepo

participant ":FloorSchema" as Schema


?o->Route: GET
activate Route

Route -> Controller: listPassagewaysBetween2BuildingsService(req, res, next)
activate Controller

Controller -> Service: listPassagewaysBetween2BuildingsService(buildingCode)
activate Service

Service -> BuildingRepo: findByBuildingCode(building1Code)
activate BuildingRepo
BuildingRepo -> BuildingSchema: findOne(building1Code)
activate BuildingSchema
BuildingRepo <-- BuildingSchema
deactivate BuildingSchema
Service <-- BuildingRepo
deactivate BuildingRepo

Service -> BuildingRepo: findByBuildingCode(building2Code)
activate BuildingRepo
BuildingRepo -> BuildingSchema: findOne(building2Code)
activate BuildingSchema
BuildingRepo <-- BuildingSchema
deactivate BuildingSchema
Service <-- BuildingRepo
deactivate BuildingRepo




Service -> Building: get all passageways of building1

Service -> Building: passagewaysList = select from the previous step the passageways that have the same id in building2 and the floor to which it connects



Service -> Map:toDtoList(passagewaysList)
activate Map

Map -> DTO: create
deactivate Map

Service --> Controller: passageways list
deactivate Service

Controller --> Route: passageways list
deactivate Controller
<--Route:



@enduml
