@startuml

autonumber
actor "Campus Manager" as CM
participant Visualização
participant "MasterDataBuilding" as GI


CM -> Visualização: Create elevator
activate Visualização

Visualização -> GI: POST elevator
activate GI


GI --> Visualização: elevator
deactivate GI

CM <-- Visualização: Informs operation success
deactivate Visualização


@enduml
