@startuml

autonumber
actor "Campus Manager" as CM
participant Visualização
participant "MasterDataBuilding" as GI

CM -> Visualização: Starts the process to create a building floor
activate Visualização
Visualização --> CM: Request data
deactivate Visualização

CM -> Visualização: Types the data
activate Visualização

Visualização -> GI: POST floor
activate GI

GI -> GI: createFloor(floor)

GI --> Visualização: floor
deactivate GI

CM <-- Visualização: Informs operation success
deactivate Visualização


@enduml
