@startuml

autonumber

participant ":ElevatorRoute" as Route
participant ":EditElevatorController" as Controller
participant ":EditElevatorService" as Service
participant ":ElevatorRepo" as Repo
participant ":ElevatorPersistence" as Persistence
participant ":ElevatorMap" as Map
participant ":ElevatorDTO" as DTO
participant ":BuildingRepo" as BuildingRepo
participant ":BuildingPersistence" as BuildingPersistence



?o->Route: GET
activate Route

Route -> Controller: listElevatorsInBuilding(req, res, next)
activate Controller

Controller -> Service: listElevatorsInBuilding(buildingCode)
activate Service

Service -> BuildingRepo: findByBuildingCode(buildingCode)
activate BuildingRepo
BuildingRepo -> BuildingPersistence: findOne(buildingCode)
activate BuildingPersistence
BuildingRepo <-- BuildingPersistence
deactivate BuildingPersistence
Service <-- BuildingRepo
deactivate BuildingRepo




Service -> Repo: get elevators which have the same id as the ones stored in building
activate Repo
Repo -> Persistence: get elevators
deactivate Repo

Service -> Map:toDto(elevators)
activate Map

Map -> DTO: create
deactivate Map

Service --> Controller: elevators list
deactivate Service

Controller --> Route: elevators list
deactivate Controller
<--Route:



@enduml
