@startuml

autonumber

participant ":PassagewayRoute" as Route
participant ":PassagewayController" as Controller
participant ":PassagewayDTO" as DTO
participant ":PassagewayService" as Service
participant ":Passageway" as Floor
participant ":PassagewayRepo" as Repo
participant ":PassagewayMap" as Map

participant ":PassagewayPersistence" as Persistence
participant ":PassagewayDTOResult" as DTOResult

?o->Route: POST
activate Route

Route -> Controller: create()
activate Controller

Controller -> DTO: toDTO()
activate DTO

DTO --> Controller:
deactivate DTO

Controller -> Service: createPassageway()
activate Service
Service -> Floor: create()

Service -> Repo: save()
activate Repo

Repo -> Map: toPersistence()
activate Map
deactivate Map

Repo -> Persistence: create()
activate Persistence
deactivate Persistence

Repo -> Map: toDomain()
activate Map
deactivate Map

Repo --> Service:
deactivate Repo

Service -> Map: toDTO()
activate Map
Map -> DTOResult: create()
activate DTOResult
deactivate DTOResult
deactivate Map

Service --> Controller:
deactivate Service

Controller --> Route:
deactivate Controller

<--Route:
deactivate Route


@enduml
