@startuml ProcessView
'https://plantuml.com/sequence-diagram

autonumber
participant RobotRoute
participant InhibitRobotController
participant InhibitRobotService
participant Robot
participant RobotMaper
participant RobotDTO
participant RobotRepo
participant RobotPersistence

?o->RobotRoute : PATCH
activate RobotRoute

RobotRoute -> InhibitRobotController : inhibitRobot(inhibitRobotDto)
activate InhibitRobotController

InhibitRobotController -> InhibitRobotService : inhibitRobot(inhibitRobotDto)
activate InhibitRobotService

InhibitRobotService -> RobotRepo : findById(id)
activate RobotRepo

RobotRepo -> RobotPersistence : findOne(query)
activate RobotPersistence

RobotPersistence --> RobotRepo
deactivate RobotPersistence

RobotRepo -> RobotMaper : toDomain(rawRobot)
activate RobotMaper

RobotMaper -> Robot : create
activate Robot

Robot --> RobotMaper
deactivate Robot

RobotMaper --> RobotRepo
deactivate RobotMaper

RobotRepo --> InhibitRobotService
deactivate RobotRepo

InhibitRobotService -> Robot : inhibitRobot()
activate Robot
deactivate Robot

InhibitRobotService -> RobotRepo : save(robot)
activate RobotRepo

RobotRepo -> RobotMaper : toPersistence()
activate RobotMaper

RobotMaper --> RobotRepo
deactivate RobotMaper

RobotRepo -> RobotPersistence : save(rawRobot)
activate RobotPersistence

RobotPersistence --> RobotRepo
deactivate RobotPersistence

RobotRepo --> InhibitRobotService
deactivate RobotRepo

InhibitRobotService -> RobotMaper : toDto()
activate RobotMaper

RobotMaper -> RobotDTO : create
deactivate Robot

RobotMaper --> InhibitRobotService
deactivate RobotMaper

InhibitRobotService --> InhibitRobotController 
deactivate InhibitRobotService

InhibitRobotController --> RobotRoute
deactivate InhibitRobotController

<-- RobotRoute
deactivate RobotRoute

@enduml