@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant Vizualization
participant MasterDataLogistics

?o-> Vizualization : disableRobot
activate Vizualization

Vizualization -> MasterDataLogistics : disableRobot
activate MasterDataLogistics

MasterDataLogistics --> Vizualization
deactivate MasterDataLogistics

<-- Vizualization
deactivate Vizualization

@enduml