@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant Vizualization
participant MasterDataBuilding

?o-> Vizualization : disableRobot
activate Vizualization

Vizualization -> MasterDataBuilding : disableRobot
activate MasterDataBuilding

MasterDataBuilding --> Vizualization
deactivate MasterDataBuilding

<-- Vizualization
deactivate Vizualization

@enduml