@startuml SequenceDiagramLevel2
'https://plantuml.com/sequence-diagram

autonumber
actor "Campus Manager" as CM
participant Visualization
participant MasterDataBuilding

CM -> Visualization : request list all buildings
activate Visualization

Visualization -> MasterDataBuilding : GET listBuildings
activate MasterDataBuilding

MasterDataBuilding -> Visualization : building list as JSON
deactivate MasterDataBuilding

Visualization -> CM
deactivate Visualization


@enduml