@startuml

skinparam linetype ortho

class ListFloorUI
class ListFloorController
class FloorService
class FloorRepo
class FloorMap
class FloorDTO

ListFloorUI .-d> ListFloorController
ListFloorController -d->FloorService
FloorService -r> FloorRepo
FloorService -d-> FloorMap
FloorMap -d-> FloorDTO

@enduml
