@startuml

autonumber
actor "Campus Manager" as CM

CM -> System: Starts the process to list building floors served by elevator
System --> CM: Request intended building
CM -> System: Types the data
CM <-- System: Shows all floors served by elevator of intended building


@enduml

