@startuml

autonumber

participant Visualization
participant "MasterDataBuilding" as GI

?o-> Visualization: List Floors with Passageways to other Buildings
activate Visualization

Visualization -> GI: GET listInBuilding
activate GI
GI --> Visualization: List of floors
deactivate GI

<-- Visualization: List of floors
deactivate Visualization


@enduml