@startuml

autonumber

participant ":FloorRoute" as Floor
participant ":ListAllFloorsController" as Controller
participant ":ListAllFloorsService" as Service
participant ":BuildingRepo" as Repo
participant ":FloorMapper" as Map
participant ":FloorDTO" as DTO

?o->Floor: GET
activate Floor

Floor -> Controller: listAllFloors(req, res, next)
activate Controller

Controller -> Service: listAllFloorsService.listAllFloors(buildingId)
activate Service

Service -> Repo: findByBuildingCode(buildingId)
activate Repo


Repo --> Service: floorList
deactivate Repo
Service -> Map: toDTO(floorList)
activate Map
Map -> DTO:create()
deactivate Map

Service --> Controller: floorListDTO
deactivate Service

Controller --> Floor: floorListDTO
deactivate Controller

<--Floor: floorListDTO
deactivate Floor


@enduml
