@startuml

autonumber

participant ":Floor" as Floor
participant ":ListFloorController" as Controller
participant ":FloorService" as Service
participant ":BuildingRepo" as Repo
participant ":BuildingMap" as Map
participant ":FloorDTO" as DTO

?o->Floor: GET
activate Floor

Floor -> Controller: getFloorsByBuilding(building)
activate Controller

Controller -> Service: getFloorsByBuilding(building)
activate Service

Service -> Repo: getFloorsByBuilding(building)
activate Repo


Repo --> Service: floorList
deactivate Repo
Service -> Map: toDTO(floorList)
activate Map
Map -> DTO:create()
deactivate Map

Service --> Controller: floorListDTO
deactivate Service

Controller --> Floor: floorListDTO
deactivate Controller

<--Floor: floorListDTO
deactivate Floor


@enduml
