@startuml

autonumber
actor "Campus Manager" as CM
participant Visualização
participant "MasterDataBuilding" as GI

CM -> Visualização: Starts the process to list all floors of a building
activate Visualização
Visualização --> CM:  Request intended building
deactivate Visualização

CM -> Visualização: Types the data
activate Visualização

Visualização -> GI: GET floorsByBuilding
activate GI
GI --> Visualização: floors(JSON)
deactivate GI

CM <-- Visualização: Shows all floors of intended building
deactivate Visualização


@enduml
