@startuml processLevel1
'https://plantuml.com/sequence-diagram

autonumber
actor "Campus Manger" as CM
participant RobDroneGo

CM -> RobDroneGo : editBuilding
activate RobDroneGo


RobDroneGo --> CM
deactivate RobDroneGo


@enduml