@startuml ProcessViewLevel3
'https://plantuml.com/sequence-diagram

autonumber
participant LoadFloorMapRoute
participant LoadFloorMapController
participant LoadFloorMapService
participant Floor
participant FloorMaper
participant FloorDTO
participant FloorRepo
participant FloorPersistence
participant Building
participant BuildingMaper
participant BuildingRepo
participant BuildingPersistence

?o->LoadFloorMapRoute : patch /uploadFloorMap
activate LoadFloorMapRoute

LoadFloorMapRoute -> LoadFloorMapController : uploadFloorMap(mapDto)
activate LoadFloorMapController

LoadFloorMapController -> LoadFloorMapService : uploadFloorMap(mapDto)
activate LoadFloorMapService

LoadFloorMapService -> BuildingRepo : findByBuildingCode()
activate BuildingRepo

BuildingRepo -> BuildingPersistence : find()
activate BuildingPersistence
deactivate BuildingPersistence

BuildingRepo -> BuildingMaper : toDomain()
activate BuildingMaper

BuildingMaper -> Building : create
activate Building

Building --> BuildingMaper
deactivate Building

BuildingMaper --> BuildingRepo
deactivate BuildingMaper

BuildingRepo --> LoadFloorMapService

deactivate BuildingRepo




LoadFloorMapService -> FloorRepo : findById(floorId)
activate FloorRepo

FloorRepo -> FloorPersistence : find()
activate FloorPersistence
FloorPersistence --> FloorRepo
deactivate FloorPersistence

FloorRepo -> FloorMaper : toDomain()
activate FloorMaper

FloorMaper -> Floor : create
activate Floor

Floor --> FloorMaper
deactivate Floor

FloorMaper --> FloorRepo 
deactivate FloorMaper

FloorRepo --> LoadFloorMapService
deactivate FloorRepo

LoadFloorMapService -> Floor : loadFloorMapAndupdate()
activate Floor

deactivate Floor

LoadFloorMapService -> FloorRepo : save()
activate FloorRepo

FloorRepo -> FloorMaper : toPersistence()
activate FloorMaper

FloorMaper --> FloorRepo
deactivate FloorMaper

FloorRepo -> FloorPersistence : save()
activate FloorPersistence
deactivate FloorPersistence

FloorRepo --> LoadFloorMapService
deactivate FloorRepo

LoadFloorMapService -> FloorMaper : toDto()
activate FloorMaper

FloorMaper -> FloorDTO : create

FloorMaper --> LoadFloorMapService
deactivate FloorMaper

LoadFloorMapService --> LoadFloorMapController
deactivate LoadFloorMapService

LoadFloorMapController --> LoadFloorMapRoute
deactivate LoadFloorMapController

<-- LoadFloorMapRoute
deactivate LoadFloorMapRoute

@enduml