@startuml

autonumber

participant ":BuildingRoute" as Floor
participant ":ListBuildingsMaxMinFloorsController" as Controller
participant ":ListBuildingsMaxMinFloorsService" as Service
participant ":BuildingRepo" as Repo
participant ":BuildingMap" as Map
participant ":BuildingDTO" as DTO

?o->Floor: GET
activate Floor

Floor -> Controller: listBuildingsByMaxAndMinFloors(req, res, next)
activate Controller

Controller -> Service: listBuildingsByMaxAndMinFloors(max,min)
activate Service

Service -> Repo: findBuildingsByMaxAndMinFloors(max,min)
activate Repo


Repo --> Service: buildingList
deactivate Repo
Service -> Map: toDTO(buildingList)
activate Map
Map -> DTO:create()
deactivate Map

Service --> Controller: buildingListDTO
deactivate Service

Controller --> Floor: buildingListDTO
deactivate Controller

<--Floor: buildingListDTO
deactivate Floor


@enduml
