@startuml

autonumber

participant ":FloorRoute" as Route
participant ":FloorController" as Controller
participant ":FloorDTO" as DTO
participant ":FloorService" as Service
participant ":FloorRepo" as Repo
participant ":FloorMap" as Map
participant ":Floor" as Floor

participant ":FloorPersistence" as Persistence
participant ":FloorDTOResult" as DTOResult

?o->Route: PUT
activate Route

Route -> Controller: update()
activate Controller

Controller -> DTO: toDTO()
activate DTO

DTO --> Controller:
deactivate DTO

Controller -> Service: updateFloor()
activate Service
Service -> Repo: findById()
activate Repo
deactivate Repo

Service -> Floor: set()
activate Floor
deactivate Floor

Service -> Repo: save()
activate Repo

Repo -> Map: toPersistence()
activate Map
deactivate Map

Repo -> Persistence: save()
activate Persistence
deactivate Persistence



Repo --> Service:
deactivate Repo

Service -> Map: toDTO()
activate Map
Map -> DTOResult: update()
activate DTOResult
deactivate DTOResult
deactivate Map

Service --> Controller:
deactivate Service

Controller --> Route:
deactivate Controller

<--Route:
deactivate Route


@enduml
