@startuml

autonumber
actor "Campus Manager" as CM
participant Visualização
participant "MasterDataBuilding" as GI

CM -> Visualização: Starts the process to edit a building floor
activate Visualização
Visualização --> CM: Request data to edit
deactivate Visualização

CM -> Visualização: Types the data
activate Visualização
Visualização --> CM: Shows actual information and request new data
deactivate Visualização

CM -> Visualização: Types the new data
activate Visualização

Visualização -> GI: PUT floor
activate GI

GI -> GI: editFloor(floor)

GI --> Visualização: floor
deactivate GI

CM <-- Visualização: Informs operation success
deactivate Visualização


@enduml
