@startuml

autonumber
actor "Campus Manager" as CM
participant Visualization
participant "MasterDataBuilding" as GI

CM -> Visualization: Edit elevator
activate Visualization

Visualization -> GI: GET listInBuilding
activate GI
GI --> Visualization: List of elevators
deactivate GI

CM <-- Visualization: List of elevators
deactivate Visualization


@enduml