@startuml

autonumber

participant ":FloorRoute" as Floor
participant ":CreateFloorController" as Controller
participant ":CreateFloorService" as Service
participant ":Floor" as Class
participant ":FloorRepo" as Repo
participant ":FloorMapper" as Map
participant ":FloorPersistence" as FloorPersistence
participant ":Building" as Building
participant ":BuildingRepo" as BuildingRepo
participant ":BuildingPersistence" as BuildingPersistence
participant ":FloorDTO" as DTO

?o->Floor: POST
activate Floor

Floor -> Controller: createFloor(req, res, next)
activate Controller



Controller -> Service: createFloor(createFloorDTO)
activate Service

Service -> Class:create

Service -> Repo: save
activate Repo

Repo -> FloorPersistence: findOne
activate FloorPersistence
deactivate FloorPersistence

Repo -> Map: toPersistence
activate Map
deactivate Map


Repo -> FloorPersistence: create
activate FloorPersistence
deactivate FloorPersistence

Repo -> Map: toDomain
activate Map
deactivate Map


Repo --> Service
deactivate Repo

Service -> Building: addFloor

Service -> BuildingRepo: save
activate BuildingRepo
BuildingRepo -> BuildingPersistence: findOne
activate BuildingPersistence
deactivate BuildingPersistence

BuildingRepo -> BuildingPersistence: save
activate BuildingPersistence
deactivate BuildingPersistence

BuildingRepo --> Service
deactivate BuildingRepo

Service -> Map: toDTO
activate Map
Map -> DTO: create
activate DTO
deactivate DTO
deactivate Map

Service --> Controller:
deactivate Service

Controller -> DTO: getValue
activate DTO
deactivate DTO

Controller -> Controller: res(201,json)

Controller --> Floor: response
deactivate Controller

<--Floor: response
deactivate Floor


@enduml
