@startuml processLevel1
'https://plantuml.com/sequence-diagram

autonumber
actor "Fleet Manger" as CM
participant RobDroneGo

CM -> RobDroneGo : disableRobot
activate RobDroneGo


RobDroneGo --> CM
deactivate RobDroneGo


@enduml