@startuml SequenceDiagramLevel2


participant Visualization
participant MasterDataBuilding

?o-> Visualization : sends building information
activate Visualization

Visualization -> MasterDataBuilding : POST createBuildingRequest
activate MasterDataBuilding

MasterDataBuilding -> Visualization : buildingJSON

deactivate MasterDataBuilding

<-- Visualization: inform success
deactivate Visualization


@enduml