@startuml SequenceDiagramLevel3
'https://plantuml.com/use-case-diagram


actor "Fleet Manager" as FM
participant Robot
participant Nickname
participant CreateFloorService
participant Floor
participant Building
participant BuildingMap
participant FloorMap
participant FloorDto
participant FloorRepo
participant BuildingRepo
database buildingDatabase
database floorDatabase

CM -> Robot : data JSON
activate Robot

Robot -> Nickname : createFloor(floorJSON, buildingCode)
activate Nickname

Nickname -> CreateFloorService : createFloor(floorDto, buildingCode)
activate CreateFloorService
activate BuildingRepo
activate FloorRepo

CreateFloorService -> BuildingRepo : findByCode(buildingCode)

BuildingRepo -> buildingDatabase : findByCode(buildingCode)

BuildingRepo -> BuildingMap : toDomain(building)
activate BuildingMap

BuildingMap -> Building : create(building)
activate Building

BuildingRepo --> CreateFloorService

CreateFloorService -> Floor : create(floorDto)
activate Floor

CreateFloorService -> Building : addFloor(floor)

CreateFloorService -> FloorRepo : save(floor)

FloorRepo -> FloorMap : toPersistence(floor)
activate FloorMap

FloorRepo -> floorDatabase : save(floorPersistence)

FloorRepo -> FloorMap : toDomain(floorPersistence)

FloorRepo --> CreateFloorService

CreateFloorService -> BuildingRepo : save(building)

BuildingRepo -> BuildingMap : toPersistence(building)

BuildingRepo -> buildingDatabase : save(building)

BuildingRepo -> BuildingMap : toDomain(building)
deactivate BuildingMap

BuildingRepo --> CreateFloorService

CreateFloorService -> FloorMap : toDto(floor)
deactivate FloorMap

deactivate Building
deactivate Floor
deactivate BuildingRepo
deactivate FloorRepo

CreateFloorService -> Nickname 
deactivate CreateFloorService

Nickname -> Robot

deactivate Nickname

Robot -> CM

deactivate Robot

@enduml