@startuml

autonumber
actor "Fleet Manager" as CM
participant Visualização
participant "MasterDataLogistics" as GI

CM -> Visualização: Starts the process to add a new robot to the fleet
activate Visualização
Visualização --> CM: Request data (type, serialNumber, Nickname, Code
deactivate Visualização

CM -> Visualização: Types the data
activate Visualização

Visualização -> GI: POST robot
activate GI

GI -> GI: createRobot(robot)

GI --> Visualização: robot
deactivate GI

CM <-- Visualização: Informs operation success
deactivate Visualização


@enduml
