@startuml

autonumber

participant ":RobotRoute" as Route
participant ":RobotController" as Controller
participant ":RobotDTO" as DTO
participant ":RobotService" as Service
participant ":Robot" as Floor
participant ":RobotRepo" as Repo
participant ":RobotMap" as Map

participant ":RobotPersistence" as Persistence
participant ":RobotDTOResult" as DTOResult

?o->Route: POST
activate Route

Route -> Controller: create()
activate Controller

Controller -> DTO: toDTO()
activate DTO

DTO --> Controller:
deactivate DTO

Controller -> Service: createRobot()
activate Service
Service -> Floor: create()

Service -> Repo: save()
activate Repo

Repo -> Map: toPersistence()
activate Map
deactivate Map

Repo -> Persistence: create()
activate Persistence
deactivate Persistence

Repo -> Map: toDomain()
activate Map
deactivate Map

Repo --> Service:
deactivate Repo

Service -> Map: toDTO()
activate Map
Map -> DTOResult: create()
activate DTOResult
deactivate DTOResult
deactivate Map

Service --> Controller:
deactivate Service

Controller --> Route:
deactivate Controller

<--Route:
deactivate Route


@enduml
