@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Fleet Manager" as CM

CM -> System: Starts the process to add a new robot to the fleet
System --> CM: Request data (type, name)
CM -> System: Types the data
CM <-- System: Informs operation success


@enduml
