@startuml

autonumber
actor "Campus Manager" as CM
participant Visualization
participant "MasterDataBuilding" as GI

CM -> Visualization: Create new room
activate Visualization

Visualization -> GI: POST createRoom
activate GI
GI --> Visualization: room(JSON)
deactivate GI

CM <-- Visualization: Inform Success
deactivate Visualization


@enduml