@startuml

autonumber
actor "Campus Manager" as CM
participant Visualização
participant "MasterDataBuilding" as GI

CM -> Visualização: Starts the process to create an elevator in a building.
activate Visualização
Visualização --> CM: Request data
deactivate Visualização

CM -> Visualização: Types the data
activate Visualização

Visualização -> GI: POST elevator
activate GI

GI -> GI: createElevator(elevator)

GI --> Visualização: elevator
deactivate GI

CM <-- Visualização: Informs operation success
deactivate Visualização


@enduml
