@startuml processView3
'https://plantuml.com/sequence-diagram

autonumber
participant EditBuildintRoute
participant EditBuildingController
participant EditBuildingService
participant BuildingMap
participant Building
participant BuildingDto
participant BuildingRepo
participant buildingPersistence

EditBuildintRoute -> EditBuildingController : editBuilding()
activate EditBuildintRoute
activate EditBuildingController

EditBuildingController -> EditBuildingService : editBuilding()
activate EditBuildingService

EditBuildingService -> BuildingRepo : findByBuildingCode()
activate BuildingRepo

BuildingRepo -> buildingPersistence : findOne()
activate buildingPersistence

buildingPersistence --> BuildingRepo
deactivate buildingPersistence

BuildingRepo -> BuildingMap : toDomain()
activate BuildingMap

BuildingMap -> Building : create
activate Building
deactivate Building

BuildingMap --> BuildingRepo
deactivate BuildingMap

BuildingRepo --> EditBuildingService
deactivate BuildingRepo

EditBuildingService -> Building : edit
activate Building
deactivate Building

EditBuildingService -> BuildingRepo : save
activate BuildingRepo

BuildingRepo -> BuildingMap : toPersistence
activate BuildingMap

BuildingMap --> BuildingRepo
deactivate BuildingMap

BuildingRepo -> buildingPersistence : save
activate buildingPersistence
deactivate buildingPersistence

BuildingRepo --> EditBuildingService
deactivate BuildingRepo

EditBuildingService -> BuildingMap : toDto
activate BuildingMap

BuildingMap -> BuildingDto : create

BuildingMap --> EditBuildingService
deactivate BuildingMap

EditBuildingService --> EditBuildingController
deactivate EditBuildingService

EditBuildingController --> EditBuildintRoute
deactivate EditBuildingController

deactivate EditBuildintRoute

@enduml