@startuml

skinparam linetype ortho

class ListBuildingUI
class ListBuildingController
class BuildingService
class BuildingRepo
class BuildingMap
class BuildingDTO

 ListBuildingUI .-d> ListBuildingController
ListBuildingController -d->BuildingService
BuildingService -r> BuildingRepo
BuildingService -d-> BuildingMap
BuildingMap -d-> BuildingDTO

@enduml
