@startuml

autonumber
actor "Campus Manager" as CM
participant Visualização
participant "Gestão de Informação" as GI

CM -> Visualização: Starts the process to  list buildings with min and max floors.
activate Visualização
Visualização --> CM: Request max and min of floors
deactivate Visualização

CM -> Visualização: Types the data
activate Visualização

Visualização -> GI: GET buildingsByMaxAndMinFloors
activate GI
GI --> Visualização: building(JSON)
deactivate GI

CM <-- Visualização: Shows buildings list
deactivate Visualização


@enduml
