@startuml sequenceDiagram
'https://plantuml.com/sequence-diagram

autonumber
actor "Campus Manager" as CM

participant CreateBuildingRoute
participant CreateBuildingController
participant CreateBuildingService
participant Building
participant BuildingDto
participant BuildingMapper
database BuildingRepo



@enduml